{% set version = "1.5.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rmisc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Rmisc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Rmisc/Rmisc_{{ version }}.tar.gz
  sha256: 1d65d5c8f93448924acb13dfb95dd419b6b2325c49da53394d15fac93b58d2c0

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-lattice
    - r-plyr
  run:
    - r-base
    - r-lattice
    - r-plyr

test:
  commands:
    - $R -e "library('Rmisc')"           # [not win]
    - "\"%R%\" -e \"library('Rmisc')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=Rmisc
  license: GPL-3.0-only
  summary: The Rmisc library contains many functions useful for data analysis and utility operations.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: Rmisc
# Type: Package
# Title: Rmisc: Ryan Miscellaneous
# Version: 1.5
# Date: 2013-10-21
# Author: Ryan M. Hope <rmh3093@gmail.com>
# Maintainer: Ryan M. Hope <rmh3093@gmail.com>
# Description: The Rmisc library contains many functions useful for data analysis and utility operations.
# License: GPL-3
# Suggests: latticeExtra, Hmisc, stats4
# Depends: lattice, plyr
# Collate: 'CI.R' 'STDERR.R' 'group.UCL.R' 'group.CI.R' 'group.STDERR.R' 'lr.glover.R' 'multiplot.R' 'panel.circle.R' 'rounder.R' 'rsi.R' 'summarySE.R'
# Packaged: 2013-10-21 19:55:26 UTC; ryanhope
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2013-10-22 00:46:56
