appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: kKzlzxgVXlsNThzop7q4pPQUr2sL8Do+eec4yjIzH1Scyzb2qo2iWR7mTUhAPVOGsbUzgJAEIlWhggrzVnBgREn9XB3uJsHh+EPXlGeVX2VTIykbc980rJZgTTQHEyaclr0KcbfYqwWzUeO97s6jGLfUrL/lLNkEwgNWye9EChszjqm2RvFInc94FNBhCnW5jqQZbm0g8GJC0mG+d2Cd1hJ/K23/znyJnARFJ3fzf0A4G3r5084vcztWSyy0HL/Uv204bSkLmwvEoqqibkodmaFqsJ2KlIuciE92DnfKhhpxWT2Yvr6JwOufeKFBmTMFAacDRCsjzTRKd9yTFWt1QwaPQFJ1QmyRs+SxhV4uXcR8m/3/6fq2g6bh/rVtJGU+Fat/lwzENU7sxSTwXIBkQm/qbKU82YzlmwGcM/pjchgwyWsTI/a7qrAgz01vAjbAnsTbVfyzAHWhhmEn0HeGh51GosPmVyBF536Vx29If3mBXz1Vs1JAaVJV+I8N8g5viGqGvTJj9h6eKYTnwQU/AWasRafTSpMpFtkbib+rX0cNqrlCIABZhq6kQczuoJcT9rmguhMcg1/z4BPADSvz+gS11nT38/e7sQ7FLMJ4ubv73AD+1T3skTTYaYvKlTR3xKGLa3UjRizDGSpDviSJWzOP2JQfSWpjWsrXDxikRXU=
conda_forge_output_validation: true
